export const lostArkBibleClassNames: Record<string, string> = {
  na: "",
  warrior: "Warrior",
  berserker: "Berserker",
  destroyer: "Destroyer",
  warlord: "Gunlancer",
  holyknight: "Paladin",
  warrior_female: "Warrior",
  berserker_female: "Slayer",
  holyknight_female: "Valkyrie",
  magician: "Mage",
  arcana: "Arcanist",
  summoner: "Summoner",
  bard: "Bard",
  elemental_master: "Sorceress",
  fighter: "Martial Artist",
  battle_master: "Wardancer",
  infighter: "Scrapper",
  force_master: "Soulfist",
  lance_master: "Glaivier",
  fighter_male: "Martial Artist",
  battle_master_male: "Striker",
  infighter_male: "Breaker",
  delain: "Assassin",
  blade: "Deathblade",
  demonic: "Shadowhunter",
  reaper: "Reaper",
  soul_eater: "Souleater",
  hunter: "Gunner",
  hawk_eye: "Sharpshooter",
  devil_hunter: "Deadeye",
  blaster: "Artillerist",
  scouter: "Machinist",
  hunter_female: "Gunner",
  devil_hunter_female: "Gunslinger",
  specialist: "Specialist",
  yinyangshi: "Artist",
  weather_artist: "Aeromancer",
  alchemist: "Wildsoul",
  dragon_human: "Guardianknight",
  dragon_knight: "Guardianknight"
};
